# Generated by Django 4.2.3 on 2023-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caf_name", models.CharField(max_length=50)),
                ("tablenum", models.PositiveIntegerField()),
            ],
        ),
    ]
